// <auto-generated />
namespace eVoting.DAL
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class SystemDataSqlClient : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SystemDataSqlClient));
        
        string IMigrationMetadata.Id
        {
            get { return "201312031352091_System.Data.SqlClient"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
